project:
  type: website
  output-dir: docs

website:
  title: "Calum Maney"
  navbar:
    pinned: true
    left:
      - text: "Home"
        href: index.qmd
      - posts.qmd
      - research.qmd
      - talks.qmd
      - text: "Experience"
        href: employment.qmd
      - text: "Education"
        href: education.qmd
      - text:  "Latest CV"
        href: CV.qmd
    right:
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:calum.maney@unep-wcmc.org"
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/calummaney
        rel: me
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
        href: https://www.linkedin.com/in/calum-maney-316a9116b/
        rel: me
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Calum Maney.</span>
      <br />
      <span class="faux-block">All content licensed under [{{< fa brands creative-commons >}}{{< fa brands creative-commons-by >}} CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>      
    center: |
      <br />
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <br />
      <span class="faux-block">Banners adapted from [Andrew Heiss](https://www.andrewheiss.com/)</span>

format:
  html:
    theme:
      - united
    css: styles.css
    toc: true

editor: visual