project:
  type: website
  output-dir: docs

website:
  title: "Calum Maney"
  navbar:
    left:
      - href: index.qmd
      - about.qmd
      - posts.qmd
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Calum Maney.</span>
      <span class="faux-block">All content licensed under [{{< fa brands creative-commons >}}{{< fa brands creative-commons-by >}} CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>      
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual